version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: myapp_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    ports:
      - "6380:6379"

  web:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/myapp_development
      REDIS_URL: redis://redis:6379/1

volumes:
  pgdata:
  bundle:
