default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] || "postgres" %>
  password: <%= ENV["DB_PASSWORD"] || "password" %>
  host: <%= ENV["DB_HOST"] || "localhost" %>

development:
  <<: *default
  database: my_app1

test:
  <<: *default
  database: my_app_1_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

cable:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

queue:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
